// h/t https://mrsvschickadees.com/2019/12/12/the-best-list-of-cvc-words-free/
export const easy = [
  { text: "bag", emoji: "🛍️", tooClose: [] },
  { text: "bed", emoji: "🛏️", tooClose: ["nap"] },
  { text: "bin", emoji: "🗑️", tooClose: [] },
  // Irregular
  // { text: "boy", emoji: "👦", tooClose: ["kid", "son", "man"] },
  { text: "bug", emoji: "🐛", tooClose: [] },
  { text: "can", emoji: "🥫", tooClose: [] },
  { text: "cap", emoji: "🧢", tooClose: [] },
  { text: "cat", emoji: "🐱", tooClose: ["pet", "dog"] },
  { text: "cop", emoji: "👮‍♂️", tooClose: ["man", "dad"] },
  { text: "cut", emoji: "✂️", tooClose: [] },
  { text: "dad", emoji: "🧔‍♂️", tooClose: ["man", "men", "cop"] },
  { text: "dog", emoji: "🐶", tooClose: [] },
  { text: "hen", emoji: "🐔", tooClose: [] },
  { text: "hog", emoji: "🐖", tooClose: ["pig"] },
  { text: "hot", emoji: "🥵", tooClose: [] },
  { text: "jet", emoji: "✈️", tooClose: [] },
  { text: "kid", emoji: "🧒", tooClose: ["son", "boy", "man"] },
  { text: "leg", emoji: "🦵", tooClose: [] },
  { text: "lip", emoji: "👄", tooClose: [] },
  { text: "log", emoji: "🪵", tooClose: [] },
  { text: "mad", emoji: "😡", tooClose: [] },
  { text: "man", emoji: "👱‍♂️", tooClose: ["dad", "men", "kid", "boy", "cop"] },
  { text: "map", emoji: "🗺️", tooClose: [] },
  { text: "men", emoji: "👬", tooClose: ["man", "dad"] },
  { text: "mom", emoji: "👩", tooClose: ["kid"] },
  { text: "mug", emoji: "☕️", tooClose: ["pot"] },
  { text: "nap", emoji: "😴", tooClose: ["bed"] },
  { text: "pan", emoji: "🍳", tooClose: [] },
  { text: "pen", emoji: "🖊️", tooClose: [] },
  { text: "pet", emoji: "🐹", tooClose: ["cat", "pig", "dog"] },
  { text: "pig", emoji: "🐷", tooClose: ["hog"] },
  { text: "pin", emoji: "📌", tooClose: [] },
  { text: "pot", emoji: "🫖", tooClose: ["mug"] },
  { text: "red", emoji: "🔴", tooClose: [] },
  { text: "run", emoji: "🏃‍♀️", tooClose: [] },
  { text: "sad", emoji: "😢", tooClose: [] },
  { text: "sob", emoji: "😭", tooClose: [] },
  // Irregular
  // { text: "son", emoji: "👨‍👦", tooClose: ["kid", "boy", "sun"] },
  { text: "sun", emoji: "☀️", tooClose: ["son"] },
  { text: "tag", emoji: "🏷️", tooClose: [] },
  { text: "ten", emoji: "🔟", tooClose: [] },
  { text: "van", emoji: "🚙", tooClose: ["car"] },
  { text: "wet", emoji: "💧", tooClose: [] },
];

export const hard = [
  { text: "cab", emoji: "🚕", tooClose: [] },
  { text: "lab", emoji: "🥼", tooClose: [] },
  { text: "wed", emoji: "", tooClose: [] },
  { text: "vet", emoji: "👩‍⚕️", tooClose: [] },
  { text: "fin", emoji: "", tooClose: [] },
  { text: "tin", emoji: "", tooClose: [] },
  { text: "win", emoji: "🏆️", tooClose: ["won"] },
  { text: "zip", emoji: "", tooClose: [] },
  { text: "lit", emoji: "", tooClose: [] },
  { text: "sit", emoji: "", tooClose: [] },
  { text: "cob", emoji: "🌽", tooClose: [] },
  { text: "won", emoji: "", tooClose: ["win"] },
  { text: "cot", emoji: "", tooClose: [] },
  { text: "bud", emoji: "", tooClose: [] },
  { text: "bun", emoji: "🍔", tooClose: [] },
];
