// h/t https://mrsvschickadees.com/2019/12/12/the-best-list-of-cvc-words-free/
export const easy = [
  { text: "dad", emoji: "🧔‍♂️", tooClose: ["man", "men"] },
  { text: "mad", emoji: "😡", tooClose: [] },
  { text: "sad", emoji: "😢", tooClose: [] },
  { text: "bag", emoji: "🛍️", tooClose: [] },
  { text: "can", emoji: "🥫", tooClose: [] },
  { text: "man", emoji: "👱‍♂️", tooClose: ["dad", "men"] },
  { text: "van", emoji: "🚙", tooClose: ["car"] },
  { text: "cap", emoji: "🧢", tooClose: [] },
  { text: "map", emoji: "🗺️", tooClose: [] },
  { text: "nap", emoji: "😴", tooClose: ["bed"] },
  { text: "cat", emoji: "🐱", tooClose: ["pet", "dog"] },
  { text: "bed", emoji: "🛏️", tooClose: ["nap"] },
  { text: "leg", emoji: "🦵", tooClose: [] },
  { text: "red", emoji: "🔴", tooClose: [] },
  { text: "men", emoji: "👬", tooClose: ["man", "dad"] },
  { text: "pen", emoji: "🖊️", tooClose: [] },
  { text: "ten", emoji: "🔟", tooClose: [] },
  { text: "jet", emoji: "✈️", tooClose: [] },
  { text: "pet", emoji: "🐹", tooClose: ["cat", "pig", "dog"] },
  { text: "kid", emoji: "🧒", tooClose: ["son", "boy"] },
  { text: "pig", emoji: "🐷", tooClose: ["hog"] },
  { text: "lip", emoji: "👄", tooClose: [] },
  { text: "dog", emoji: "🐶", tooClose: [] },
  { text: "hog", emoji: "🐖", tooClose: ["pig"] },
  { text: "log", emoji: "🪵", tooClose: [] },
  { text: "son", emoji: "👨‍👦", tooClose: ["kid", "boy"] },
  { text: "pot", emoji: "🫖", tooClose: [] },
  { text: "boy", emoji: "👦", tooClose: ["kid", "son"] },
  { text: "bug", emoji: "🐛", tooClose: [] },
  { text: "run", emoji: "🏃‍♀️", tooClose: [] },
  { text: "sun", emoji: "☀️", tooClose: [] },
];

export const hard = [
  { text: "cab", emoji: "", tooClose: [] },
  { text: "lab", emoji: "", tooClose: [] },
  { text: "tag", emoji: "", tooClose: [] },
  { text: "pan", emoji: "🍳", tooClose: [] },
  { text: "wed", emoji: "", tooClose: [] },
  { text: "hen", emoji: "🐔", tooClose: [] },
  { text: "vet", emoji: "", tooClose: [] },
  { text: "wet", emoji: "", tooClose: [] },
  { text: "bin", emoji: "", tooClose: [] },
  { text: "fin", emoji: "", tooClose: [] },
  { text: "pin", emoji: "", tooClose: [] },
  { text: "tin", emoji: "", tooClose: [] },
  { text: "win", emoji: "", tooClose: [] },
  { text: "zip", emoji: "", tooClose: [] },
  { text: "lit", emoji: "", tooClose: [] },
  { text: "sit", emoji: "", tooClose: [] },
  { text: "cob", emoji: "", tooClose: [] },
  { text: "sob", emoji: "", tooClose: [] },
  { text: "won", emoji: "", tooClose: [] },
  { text: "cop", emoji: "", tooClose: [] },
  { text: "cot", emoji: "", tooClose: [] },
  { text: "hot", emoji: "", tooClose: [] },
  { text: "bud", emoji: "", tooClose: [] },
  { text: "bun", emoji: "🍔", tooClose: [] },
  { text: "mug", emoji: "", tooClose: [] },
  { text: "cut", emoji: "", tooClose: [] },
];
